export enum PATHS {
  ROOT = '',
  HOME = 'home',
  AUTH = 'auth',
  USERS = 'users',
  TEACHERS = 'teachers',
  STUDENTS = 'students',
  ROLES = 'roles',
  PERMISSIONS = 'permissions',
  COURSES = 'courses',
  ENROLLMENTS = 'enrollments',
  CITIES = 'cities',
  QUESTIONS = 'questions',
  ANSWERS = 'answers',
}

export enum ROUTES {
  ROOT = '/',
  HOME = '/home',
  AUTH = '/auth',
  USERS = '/users',
  TEACHERS = '/teachers',
  STUDENTS = '/students',
  ROLES = '/roles',
  PERMISSIONS = '/permissions',
  COURSES = '/courses',
  ENROLLMENTS = '/enrollments',
  CITIES = '/cities',
  QUESTIONS = '/questions',
  ANSWERS = '/answers',
}

export enum MENU_LABELS {
  // ROOT = '/',
  HOME = 'Inicio',
  // AUTH = 'AUthentication',
  USERS = 'Usuarios',
  TEACHERS = 'Profesores',
  STUDENTS = 'Estudiantes',
  ROLES = 'Roles',
  PERMISSIONS = 'Permisos',
  COURSES = 'Cursos',
  ENROLLMENTS = 'Inscripciones',
  CITIES = 'Ciudades',
  QUESTIONS = 'Preguntas',
  ANSWERS = 'Respuestas',
}